version: '3'
services:
  mongo:
    image: mongo:3.4.10
    volumes:
      - ./docker/mongo:/data/db
      - ./docker/dump:/dump
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "27017:27017"
  ruby:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./repos:/var/www/shirasagi
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
      - RAILS_ENV=development
    links:
      - mongo
      - mail
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mail:
    build:
      context: docker/mail
      command: /root/start.sh
      volumes:
        - ./docker/mail_data:/var/spool/virtual
        - ./docker/mail/etc/dovecot:/etc/dovecot
        - ./docker/mail/etc/postfix:/etc/postfix
      expose:
        - "25"
        - "110"
        - "143"
        - "993"
        - "995"
      environment:
        - TZ=Asia/Tokyo
volumes:
  bundle_cache:
