version: '3'
services:
  mongo:
    image: mongo:3.4.5
    volumes:
      - ./docker/mongo:/data/db
      - ./docker/dump:/dump
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "27017:27017"
  ruby:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./repos:/var/www/shirasagi
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
    links:
      - mongo
    depends_on:
      - mongo
    stdin_open: true
    tty: true

